<?php
declare(strict_types=1);

/**
 * Admin translations - 2FA.
 */

return [
    'admin.2fa.btn_setup' => 'Enable 2FA and login',
    'admin.2fa.btn_verify' => 'Verify and log in',
    'admin.2fa.cancel_link' => 'Cancel / Log out',
    'admin.2fa.code_label' => 'Code from the app',
    'admin.2fa.err_invalid_code' => 'Invalid code. Please check your phone clock is in sync.',
    'admin.2fa.err_rate_limit' => 'Too many attempts. Please wait a moment and try again.',
    'admin.2fa.err_setup_code' => 'The code does not match. Please scan or re-enter the key and check the time synchronization.',
    'admin.2fa.err_setup_save' => 'Failed to save 2FA. Run sql/2fa_admins.sql in the database first.',
    'admin.2fa.logo_sub' => '2-Step Verification',
    'admin.2fa.page_title' => 'Two-step verification - OilCorp',
    'admin.2fa.setup_hint' => 'Type: time-based (TOTP) - 6 digits - every 30 s',
    'admin.2fa.setup_step_account_prefix' => 'Account name:',
    'admin.2fa.setup_step_account_suffix' => 'and you will find the key below:',
    'admin.2fa.setup_step_app_prefix' => 'Install the App',
    'admin.2fa.setup_step_app_suffix' => '(or Authy / Microsoft Authenticator).',
    'admin.2fa.setup_step_key_label' => 'Enter configuration key',
    'admin.2fa.setup_step_key_prefix' => 'Add an account and select',
    'admin.2fa.setup_title' => 'Set up Google Authenticator',
    'admin.2fa.verify_hint' => 'Enter the 6-digit code displayed in the authentication app.',
    'admin.2fa.verify_title' => 'Enter code generated by your application',
];
