<?php
declare(strict_types=1);

/**
 * World Map — regions, locations, JS.
 * Mapa swiata — regiony, lokalizacje, JS.
 * Keys: 84
 */

return [

    'world_map.err_bankrupt' => 'Firma jest w restrukturyzacji. Zakup odwiertów jest zablokowany.',
    'world_map.err_location_unavailable' => 'Lokalizacja jest niedostępna.',
    'world_map.err_location_occupied' => 'Ta lokalizacja jest już zajęta przez innego gracza.',
    'world_map.err_already_own' => 'Masz już odwiert w tej lokalizacji.',
    'world_map.err_well_limit' => 'Osiągnięto limit 10 odwiertów.',
    'world_map.err_insufficient_funds' => 'Brak środków. Potrzebujesz :cost PLN.',
    'world_map.msg_purchased' => 'Kupiono odwiert: :name (:region). Przydziel pracowników, aby rozpocząć produkcję.',
    'world_map.msg_reservoir_partial' => ' Złoże częściowo wyczerpane (:pct% pozostało).',
    'world_map.err_tx_failed' => 'Błąd transakcji: :msg',
    'world_map.err_system' => 'Błąd systemu.',
    'worldmap.err_bankrupt' => 'Firma jest w restrukturyzacji. Zakup odwiertów jest zablokowany.',
    'worldmap.err_location_unavailable' => 'Lokalizacja niedostępna.',
    'worldmap.err_location_occupied' => 'Ta lokalizacja jest już zajęta przez innego gracza.',
    'worldmap.err_already_own' => 'Masz już odwiert w tej lokalizacji.',
    'worldmap.err_well_limit' => 'Osiągnięto limit 10 odwiertów.',
    'worldmap.err_insufficient_funds' => 'Brak środków. Potrzebujesz :cost PLN.',
    'worldmap.err_transaction' => 'Błąd transakcji. Spróbuj ponownie.',
    'worldmap.err_system' => 'Błąd systemu. Skontaktuj się z administratorem.',
    'worldmap.msg_well_purchased' => 'Odwiert uruchomiony: :name (:region). Produkcja: :prod bbl/h.',
    'map_js.prod_bonus' => 'Bonus produkcji',
    'map_js.tax_rate' => 'Podatek/h',
    'map_js.political_risk' => 'Ryzyko polit.',
    'map_js.entry_cost' => 'Koszt wejścia',
    'map_js.badge_mine' => 'Twój',
    'map_js.badge_taken' => 'Zajęty',
    'map_js.badge_free' => 'Wolny',
    'map_js.est_production' => 'Szac. produkcja',
    'map_js.oil_richness' => 'Zasobność złoża',
    'map_js.regional_tax' => 'Podatek region.',
    'map_js.buy_cost' => 'Koszt zakupu',
    'map_js.no_funds_title' => 'Brak środków',
    'map_js.no_funds_diff' => 'Potrzebujesz jeszcze :amount PLN',
    'map_js.location_label' => 'Lokalizacja',
    'map_js.region_label' => 'Region',
    'map_js.regional_tax_row' => 'Podatek regionalny',
    'map_js.tax_suffix' => '%/h przychodu',
    'map_js.buy_btn' => 'Kup odwiert - :cost PLN',
    'map_js.buying' => 'Kupowanie...',
    'map_js.buy_confirm_title' => 'Potwierdź zakup',
    'map_js.buy_confirm_text' => 'Kupić odwiert w lokalizacji :location za :cost PLN?',
    'map_js.buy_confirm_btn' => 'Kup odwiert',
    'map_js.buy_success_title' => 'Zakup odwiertu',
    'map_js.buy_error_title' => 'Zakup odwiertu',
    'map_js.err_connection' => 'Błąd połączenia. Spróbuj ponownie.',
    'map_js.no_locations' => 'Brak lokalizacji w tym regionie.',
    'map_js.offshore' => 'Morski',
    'map_js.onshore' => 'Lądowy',
    'map_js.my_well' => 'Masz tutaj odwiert (#:id)',
    'map_js.taken_badge' => 'Ta lokalizacja jest zajęta',
    'map_js.map_error' => 'Nie można załadować mapy - sprawdź połączenie z internetem.',
    'map_js.map_error_sub' => 'Wymagany dostęp do cdnjs.cloudflare.com',
    'map.page_title' => 'Mapa Świata — OilCorp',
    'map.region_legend' => 'Podatek',
    'map.sidebar_prompt' => 'Kliknij region lub pinezkę na mapie aby zobaczyć szczegóły i kupić odwiert.',
    'map.locations_available' => 'Dostępne lokalizacje',
    'map.back_to_region' => '← Wróć do regionu',
    'map.filter_label' => 'Filtruj:',
    'map.filter_all' => 'Wszystkie',
    'map.tier_starter' => 'Starter',
    'map.tier_medium' => 'Średni',
    'map.tier_advanced' => 'Zaawansowany',
    'map.sort_label' => 'Sortuj:',
    'map.sort_default' => 'Domyślnie',
    'map.sort_price_asc' => 'Cena rosnąco',
    'map.sort_price_desc' => 'Cena malejąco',
    'map.sort_prod_asc' => 'Prod. rosnąco',
    'map.sort_prod_desc' => 'Prod. malejąco',
    'map.browse_all_btn' => 'Przeglądaj wszystkie',
    'map.back_btn' => 'Wróć',
    'map.browse_title' => 'Wszystkie odwierty',
    'map_js.well_status' => 'Status',
    'map_js.well_production' => 'Produkcja',
    'map_js.well_condition' => 'Stan techniczny',
    'map_js.well_level' => 'Poziom',
    'map_js.well_status_active' => 'Aktywny',
    'map_js.well_status_paused_cash' => 'Wstrzymany - brak środków',
    'map_js.well_status_paused_storage' => 'Wstrzymany - pełny magazyn',
    'map_js.well_status_paused_staff' => 'Wstrzymany - brak personelu',
    'map_js.well_status_broken' => 'Uszkodzony',
    'map_js.well_status_blowout' => 'Wybuch',
    'map_js.well_status_contaminated' => 'Skażony',
    'map_js.well_status_seized' => 'Zajęty przez komornika',
    'map_js.well_status_servicing' => 'W naprawie',
    'map_js.well_go_technical' => 'Przejdź do działu technicznego',
    'map_js.no_filter_results' => 'Brak wyników dla wybranych filtrów.',

];
