<?php
declare(strict_types=1);

/**
 * Admin translations - gm.
 * Tlumaczenia admina - gm.
 */

return [
    'admin.gm.broadcast_confirm' => 'Czy na pewno wysłać broadcast do WSZYSTKICH aktywnych graczy?',
    'admin.gm.broadcast_desc' => 'Wysyła wiadomość jako zdarzenie HR do wszystkich aktywnych graczy.',
    'admin.gm.broadcast_label_msg' => 'Treść',
    'admin.gm.broadcast_label_title' => 'Tytuł',
    'admin.gm.broadcast_msg_ph' => 'Treść wiadomości...',
    'admin.gm.broadcast_submit' => 'Wyślij broadcast',
    'admin.gm.broadcast_title' => 'Broadcast do graczy',
    'admin.gm.broadcast_title_ph' => 'np. Aktualizacja serwera',
    'admin.gm.bulk_confirm' => 'Czy na pewno zmienić gotówkę WSZYSTKIM aktywnym graczom?',
    'admin.gm.bulk_desc' => 'Dodaje lub odejmuje gotówkę wszystkim aktywnym graczom jednocześnie.',
    'admin.gm.bulk_submit' => 'Zastosuj',
    'admin.gm.bulk_title' => 'Globalna zmiana gotówki',
    'admin.gm.cleanup_confirm' => 'Czy na pewno wyczyścić stare dane z bazy?',
    'admin.gm.cleanup_desc' => 'Usuwa: wygasłych kandydatów, stare logi (90 dni), zakończone rekrutacje (7 dni), przeczytane zdarzenia HR (30 dni).',
    'admin.gm.cleanup_submit' => 'Wyczyść bazę',
    'admin.gm.cleanup_title' => 'Czyszczenie bazy danych',
    'admin.gm.clone_confirm' => 'Czy na pewno utworzyć klon tego konta?',
    'admin.gm.clone_desc' => 'Tworzy nowe konto z taką samą gotówką, odwiertami i magazynem jak konto źródłowe.',
    'admin.gm.clone_email_label' => 'Email nowego konta',
    'admin.gm.clone_email_ph' => 'test@oilempire.pl',
    'admin.gm.clone_pass_label' => 'Hasło',
    'admin.gm.clone_pass_ph' => 'min. 6 znaków',
    'admin.gm.clone_source_label' => 'Konto źródłowe',
    'admin.gm.clone_submit' => 'Sklonuj konto',
    'admin.gm.clone_title' => 'Klonuj konto testowe',
    'admin.gm.econ_broken' => 'Awarie',
    'admin.gm.econ_cash_avg' => 'Średnia gotówka',
    'admin.gm.econ_cash_total' => 'Gotówka w grze',
    'admin.gm.econ_condition' => 'Śr. stan tech.',
    'admin.gm.econ_cron' => 'Cron status',
    'admin.gm.econ_cron_ago' => 'min temu',
    'admin.gm.econ_cron_none' => '— brak —',
    'admin.gm.econ_debt' => 'ączny dług',
    'admin.gm.econ_loans' => 'Aktywne pożyczki',
    'admin.gm.econ_oil_price' => 'Cena ropy',
    'admin.gm.econ_players' => 'Gracze aktywni',
    'admin.gm.econ_prod' => 'Produkcja/h',
    'admin.gm.econ_staff' => 'Zarząd / Inżynierowie',
    'admin.gm.econ_title' => '📊 Ekonomia globalna',
    'admin.gm.econ_wells' => 'Odwierty',
    'admin.gm.reset_cash_label' => 'Startowa gotówka (PLN)',
    'admin.gm.reset_confirm' => 'Ta operacja jest NIEODWRACALNA. Wszystkie dane gracza zostaną usunięte. Czy na pewno kontynuować?',
    'admin.gm.reset_confirm_btn' => 'Resetuj',
    'admin.gm.reset_confirm_title' => 'Reset konta gracza',
    'admin.gm.reset_desc' => 'Usuwa WSZYSTKIE dane gracza (odwierty, pożyczki, pracowników, zadania) i resetuje konto do stanu początkowego.',
    'admin.gm.reset_player_label' => 'Gracz',
    'admin.gm.reset_submit' => 'Resetuj gracza',
    'admin.gm.reset_title' => 'Reset gracza',
    'admin.gm.select_player' => 'wybierz gracza',
    'admin.gm.title' => '🎮 Narzędzia Game Mastera',
];
