-- Skrypt do bazy danych (phpMyAdmin lub inna konsola MySQL)
-- Dodaje nowe działy (B2B, Ochrona, Sabotaże i Pozwolenia) do pomocy w grze
-- Aktualizuje istniejący dział "Pracownicy" oraz "Huby logistyczne"
-- Wersja z dodanymi tlumaczeniami angielskimi (title_en, content_en)

-- 1. Dodanie kolumn jesli to nie zostalo jeszcze zrobione:
ALTER TABLE `game_help_pages` 
ADD COLUMN `title_en` VARCHAR(255) NULL AFTER `title`,
ADD COLUMN `content_en` MEDIUMTEXT NULL AFTER `content`;

-- 2. Dodanie 3 nowych działów z EN
INSERT INTO `game_help_pages` (`slug`, `title`, `title_en`, `icon`, `sort_order`, `content`, `content_en`) VALUES 
('kontrakty_b2b', 'Kontrakty długoterminowe B2B', 'Long-term B2B Contracts', '🤝', 11, 
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Czym są Kontrakty B2B? 💼</h3>\n<p class="help-p">Zamiast sprzedawać ropę jednorazowo na rynku, możesz nawiązać z zewnętrznymi firmami długoterminowe umowy (Business-to-Business). Oferują one stabilność, ale niosą też ryzyko.</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Krok 1 — Zabezpieczenie i podpisanie umowy 💰</h3>\n<p class="help-p">Aby podpisać umowę, musisz posiadać określoną <strong>kaucję (zabezpieczenie finansowe)</strong>. Środki te są zamrażane na czas trwania umowy. Jeśli nie będziesz miał ropy na dostawę – stracisz je!</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Krok 2 — Harmonogram i Reputacja Kontraktowa ⭐</h3>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Regularne dostawy:</strong> Ropa z Twojego magazynu będzie automatycznie pobierana w wyznaczonym cyklu rozliczeniowym (np. co 5 ticków).</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Reputacja Kontraktowa:</strong> Każda udana dostawa buduje Twoją <em>Reputację Kontraktową</em> (jest ona niezależna od wiarygodności ogólnej). Z kolei pomijanie dostaw drastycznie ją obniża.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Blokada dostępu:</strong> Jeśli Twoja reputacja kontraktowa spadnie zbyt nisko, nowe, bardziej lukratywne firmy odmówią z Tobą współpracy.</li>\n</ul>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Krok 3 — Zerwanie kontraktu 🛑</h3>\n<p class="help-p">Jeśli wpadniesz w tarapaty, zawsze możesz ręcznie zerwać kontrakt. Wiąże się to jednak z potężną <strong>karą finansową</strong> oraz natychmiastowym utraceniem wpłaconej kaucji.</p>',
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">What are B2B Contracts? 💼</h3>\n<p class="help-p">Instead of selling oil once on the market, you can sign long-term agreements (Business-to-Business) with external companies. They offer stability, but also carry risks.</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Step 1 — Security deposit and signing 💰</h3>\n<p class="help-p">To sign a contract, you must have a specific <strong>security deposit</strong>. These funds are frozen for the duration of the agreement. If you do not have oil for delivery – you will lose them!</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Step 2 — Schedule and Contract Reputation ⭐</h3>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Regular deliveries:</strong> Oil from your storage will be automatically withdrawn in the designated billing cycle (e.g. every 5 ticks).</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Contract Reputation:</strong> Each successful delivery builds your <em>Contract Reputation</em> (independent of general credibility). Missing deliveries drastically lowers it.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Access block:</strong> If your contract reputation drops too low, new, more lucrative companies will refuse to work with you.</li>\n</ul>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Step 3 — Breaking the contract 🛑</h3>\n<p class="help-p">If you get into trouble, you can always manually break the contract. However, this involves a massive <strong>financial penalty</strong> and the immediate loss of the paid deposit.</p>'),

('sabotaze', 'Dział Prawny: Sabotaże i Pozwolenia', 'Legal Dept: Sabotages and Permits', '⚖️', 12, 
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Pozwolenia na Wiercenie i Łapówki 📜</h3>\n<p class="help-p">Aby rozpocząć wydobycie (lub budowę Huba Logistycznego) w nowym regionie, musisz najpierw wystąpić o <strong>Zezwolenie (Permit)</strong>. Wnioski procesowane są w dziale prawnym.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Decyzja urzędu:</strong> Wniosek może zostać rozpatrzony pozytywnie (<em>Granted</em>), opóźniony lub całkowicie odrzucony (<em>Refused</em>), co nakłada na Ciebie przymusową pauzę (cooldown) przed kolejną próbą.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Załatw to po cichu:</strong> Możesz spróbować przyspieszyć sprawy lub obejść odmowę za pomocą <em>łapówki</em>. Udana próba natychmiast przyznaje Ci zezwolenie. Wpadka sprawi jednak, że urząd się zaweźmie (znacznie dłuższa blokada), zapłacisz karę, a w Twojej historii zapisze się poważny incydent!</li>\n</ul>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Sabotaże i nieczyste zagrywki 🥷</h3>\n<p class="help-p">Naftowy biznes bywa bezwzględny. W swoim <strong>Dziale Prawnym</strong> znajdziesz też sekcję poświęconą sabotażom, dzięki którym zaszkodzisz konkurencji lub odpowiesz na jej ataki.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Ataki Korporacyjne (PvP):</strong> Możesz zlecać płatne akcje skierowane przeciwko innym graczom, np. brudne kampanie obniżające ich <em>Wiarygodność</em> lub nagłe kontrole kończące się potężnymi karami finansowymi uderzającymi w ich budżet.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Ryzyko na drodze:</strong> Twój transport drogowy (ciężarówki przewożące ropę) bywa losowo narażony na systemowe <strong>napady i kradzieże</strong> surowca, co może generować ogromne ubytki.</li>\n</ul>',
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Drilling Permits and Bribes 📜</h3>\n<p class="help-p">To start drilling (or build a Logistics Hub) in a new region, you must first apply for a <strong>Permit</strong>. Applications are processed in the legal department.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Official decision:</strong> The application can be approved (<em>Granted</em>), delayed or completely rejected (<em>Refused</em>), which imposes a mandatory pause (cooldown) before the next attempt.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Handle it quietly:</strong> You can try to speed things up or bypass a refusal with a <em>bribe</em>. A successful attempt grants you a permit immediately. However, getting caught will cause the office to crack down (much longer blockade), you will pay a fine, and a serious incident will be recorded in your history!</li>\n</ul>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Sabotages and dirty plays 🥷</h3>\n<p class="help-p">The oil business can be ruthless. In your <strong>Legal Department</strong> you will also find a section dedicated to sabotages, thanks to which you can harm your competitors or respond to their attacks.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Corporate Attacks (PvP):</strong> You can order paid actions directed against other players, e.g. dirty campaigns lowering their <em>Credibility</em> or sudden inspections ending with massive financial penalties hitting their budget.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Risks on the road:</strong> Your road transport (trucks transporting oil) is sometimes randomly exposed to systemic <strong>assaults and thefts</strong> of the raw material, which can generate huge losses.</li>\n</ul>'),

('ochrona', 'Ochrona Aktywów', 'Asset Protection', '🛡️', 13, 
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Zatrudnianie Ochrony 👮</h3>\n<p class="help-p">Aby ustrzec się przed atakami, możesz zatrudnić wyspecjalizowane agencje ochrony, które zabezpieczą Twoją infrastrukturę.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Ochrona infrastruktury:</strong> Ochronę wykupuje się na określoną liczbę cykli (ticków) dla konkretnego celu – np. dla wybranego odwiertu i pracujących tam ciężarówek.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Redukcja kradzieży:</strong> Aktywna ochrona znacząco redukuje prawdopodobieństwo, że Twój transport zostanie napadnięty, a ropa rozkradziona w trakcie kursu. Zabezpiecza Cię to przed ogromnymi stratami!</li>\n</ul>',
'<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Hiring Security 👮</h3>\n<p class="help-p">To protect yourself from attacks, you can hire specialized security agencies to secure your infrastructure.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Infrastructure protection:</strong> Protection is purchased for a specific number of cycles (ticks) for a specific target - e.g. for a selected well and the trucks working there.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Theft reduction:</strong> Active protection significantly reduces the probability that your transport will be attacked and the oil stolen during the course. This protects you from huge losses!</li>\n</ul>')
ON DUPLICATE KEY UPDATE `content` = VALUES(`content`), `content_en` = VALUES(`content_en`), `title` = VALUES(`title`), `title_en` = VALUES(`title_en`), `icon` = VALUES(`icon`);


-- 3. Dopisanie informacji do działu "Pracownicy" (o szkoleniach, cechach i strajkach)
UPDATE `game_help_pages` 
SET `content` = CONCAT(`content`, '\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 30px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Szkolenia i Cechy Personelu 🎓</h3>\n<p class="help-p">Twój personel techniczny to nie są bezimienne maszyny. Mają oni swoje unikalne cechy, takie jak <strong>Lojalność, Ryzyko korupcji czy Ambicja</strong>. Cechy te wpływają bezpośrednio na ich wydajność i roszczeniowość.</p>\n<p class="help-p">Aby poprawić umiejętności i morale załogi, wysyłaj ich na <strong>Szkolenia</strong> dostępne w zakładce HR. Przeszkolony pracownik pracuje szybciej i odblokowuje nowe bonusy.</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Strajki i Żądania Podwyżek 📢</h3>\n<p class="help-p">Gdy morale załogi spadnie lub uznają, że zarabiają za mało, mogą wystosować <strong>Żądanie Podwyżki</strong>.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Twoje opcje:</strong> Możesz zaakceptować pełną kwotę, wysłać mniejszą kontrofertę (w czym bardzo pomaga pracownik na stanowisku <em>Negocjator Płacowy</em>), odrzucić żądanie, lub je odroczyć.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Strajk:</strong> Zbyt wiele odrzuconych próśb i niskie morale doprowadzą do eskalacji i strajku. Będziesz zmuszony zasiąść do wielorundowych negocjacji. Twoje szanse na tanią ugodę zależą od skilli przypisanego Zarządu HR!</li>\n</ul>'),
`content_en` = CONCAT(IFNULL(`content_en`, ''), '\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 30px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Staff Training and Traits 🎓</h3>\n<p class="help-p">Your technical staff are not nameless machines. They have their own unique traits, such as <strong>Loyalty, Corruption Risk or Ambition</strong>. These traits directly affect their performance and demands.</p>\n<p class="help-p">To improve the skills and morale of the crew, send them to <strong>Trainings</strong> available in the HR tab. A trained employee works faster and unlocks new bonuses.</p>\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Strikes and Raise Demands 📢</h3>\n<p class="help-p">When crew morale drops or they think they earn too little, they can issue a <strong>Raise Demand</strong>.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Your options:</strong> You can accept the full amount, send a smaller counteroffer (a <em>Wage Negotiator</em> employee helps a lot with this), reject the request, or postpone it.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Strike:</strong> Too many rejected requests and low morale will lead to escalation and a strike. You will be forced to sit down to multi-round negotiations. Your chances of a cheap settlement depend on the skills of the assigned HR Board!</li>\n</ul>')
WHERE `slug` = 'pracownicy' 
  AND `content` NOT LIKE '%Szkolenia i Cechy Personelu%'; -- Ochrona przed podwójnym dodaniem


-- 4. Dopisanie informacji do działu "Huby logistyczne" (o trybach pracy)
UPDATE `game_help_pages` 
SET `content` = CONCAT(`content`, '\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 30px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Zarządzanie Trybem Pracy Huba ⚙️</h3>\n<p class="help-p">Właściciele Hubów oraz ich główni najemcy mogą w dowolnej chwili zarządzać trybem pracy swojego węzła logistycznego, dostosowując go do aktualnej sytuacji budżetowej.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Eco:</strong> Hub pracuje wolniej i zapewnia mniejszą przepustowość transportu, ale jego koszty utrzymania drastycznie spadają. Idealny na czasy kryzysu.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Standard:</strong> Zrównoważone utrzymanie.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Turbo:</strong> Znacznie podnosi maksymalną przepustowość rurociągów podpiętych pod Hub, ale generuje olbrzymie koszty utrzymania.</li>\n</ul>'),
`content_en` = CONCAT(IFNULL(`content_en`, ''), '\n\n<h3 style="color: #c8a84b; font-size: 1.05rem; margin-top: 30px; margin-bottom: 12px; border-bottom: 1px solid rgba(200,168,75,0.25); padding-bottom: 8px;">Managing Hub Work Modes ⚙️</h3>\n<p class="help-p">Hub owners and their main tenants can manage the work mode of their logistics node at any time, adapting it to the current budget situation.</p>\n<ul style="padding-left: 20px; list-style-type: square; margin-bottom: 16px;">\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Eco:</strong> The Hub works slower and provides lower transport throughput, but its maintenance costs drop drastically. Ideal for times of crisis.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Standard:</strong> Balanced maintenance.</li>\n    <li class="help-p" style="margin-bottom: 8px;"><strong>Turbo:</strong> Significantly increases the maximum throughput of pipelines connected to the Hub, but generates massive maintenance costs.</li>\n</ul>')
WHERE `title` LIKE '%Huby logistyczne%' 
  AND `content` NOT LIKE '%Trybem Pracy Huba%'; -- Ochrona przed podwójnym dodaniem
