<?php
$logisticsClientConfig['staffing'] = [
    'post_url' => function_exists('url') ? url('logistics') : '/logistics',
    'csrf_token' => CSRF::generateToken(),
    'locale' => $locale,
    'heading' => t('logistics.hub.staffing.modal_title'),
    'subtitle' => t('logistics.hub.staffing.modal_subtitle'),
    'runtime_on' => t('logistics.hub.staffing.runtime_on'),
    'runtime_off' => t('logistics.hub.staffing.runtime_off'),
    'coverage' => t('logistics.hub.staffing.coverage'),
    'skill' => t('logistics.hub.staffing.skill'),
    'morale' => t('logistics.hub.staffing.morale'),
    'effect_throughput' => t('logistics.hub.staffing.effect_throughput', ['value' => '{value}']),
    'effect_incident' => t('logistics.hub.staffing.effect_incident', ['value' => '{value}']),
    'effect_maintenance' => t('logistics.hub.staffing.effect_maintenance', ['value' => '{value}']),
    'missing_roles' => t('logistics.hub.staffing.missing_roles'),
    'active_team' => t('logistics.hub.staffing.active_team'),
    'available_team' => t('logistics.hub.staffing.available_team'),
    'empty' => t('logistics.hub.staffing.empty'),
    'empty_card' => t('logistics.hub.staffing.empty_card'),
    'role_hub_operator' => t('logistics.hub.staffing.role_hub_operator'),
    'source_board_member' => t('logistics.hub.staffing.source_board_member'),
    'source_technical_staff' => t('logistics.hub.staffing.source_technical_staff'),
    'status_active' => t('logistics.hub.staffing.status_active'),
    'status_busy' => t('logistics.hub.staffing.status_busy'),
    'status_on_leave' => t('logistics.hub.staffing.status_on_leave'),
    'status_fired' => t('logistics.hub.staffing.status_fired'),
    'status_unknown' => t('logistics.hub.staffing.status_unknown'),
    'relation_normal' => t('logistics.hub.staffing.relation_normal'),
    'relation_on_strike' => t('logistics.hub.staffing.relation_on_strike'),
    'relation_leaving' => t('logistics.hub.staffing.relation_leaving'),
    'relation_inactive' => t('logistics.hub.staffing.relation_inactive'),
    'free_allocation' => t('logistics.hub.staffing.free_allocation'),
    'current_allocation' => t('logistics.hub.staffing.current_allocation'),
    'allocation' => t('logistics.hub.staffing.allocation'),
    'btn_assign' => t('logistics.hub.staffing.btn_assign'),
    'btn_update' => t('logistics.hub.staffing.btn_update'),
    'btn_release' => t('logistics.hub.staffing.btn_release'),
    'btn_manage' => t('logistics.hub.staffing.btn_manage'),
    'confirm_release' => t('logistics.hub.staffing.confirm_release'),
    'confirm_assign' => t('logistics.hub.staffing.confirm_assign'),
    'confirm_update' => t('logistics.hub.staffing.confirm_update'),
    'no_specialization' => t('logistics.hub.staffing.no_specialization'),
    'hubs' => $hubStaffingViewByHub,
];

$logisticsClientConfig['hub'] = [
    'api' => '/src/HubApi.php',
    'csrf_token' => CSRF::generateToken(),
    'lang' => [
 // Stan i ladowanie / State and loading
    'loading'        => t('logistics.loading'),
    'err_generic'    => t('logistics.hub.err_generic'),
 // Dialogi tytuly i przyciski / Dialog titles and buttons
    'title_info'     => t('logistics.hub.title_info'),
    'title_error'    => t('logistics.hub.title_error'),
    'title_warning'  => t('logistics.hub.title_warning'),
    'confirm_title'  => t('logistics.hub.confirm_title'),
    'confirm_label'  => t('logistics.hub.confirm_label'),
 // Akcje sukcesu / Success messages
    'ok_build'       => t('logistics.hub.ok_build'),
    'ok_repair'      => t('logistics.hub.ok_repair'),
    'ok_upgrade'     => t('logistics.hub.ok_upgrade',     ['level' => '{level}']),
    'ok_mode'        => t('logistics.hub.ok_mode',        ['mode'  => '{mode}']),
    'ok_pause'       => t('logistics.hub.ok_pause'),
    'ok_resume'      => t('logistics.hub.ok_resume'),
    'ok_assign'      => t('logistics.hub.ok_assign'),
    'ok_detach'      => t('logistics.hub.ok_detach'),
    'ok_transfer'    => t('logistics.hub.ok_transfer'),
 // Potwierdzenia operacji / Confirm dialogs
    'repair_confirm'  => t('logistics.hub.repair_confirm',  ['cost' => '{cost}']),
    'upgrade_confirm' => t('logistics.hub.upgrade_confirm', ['cost' => '{cost}']),
    'detach_confirm'  => t('logistics.hub.wells_detach_confirm', ['id' => '{id}']),
 // Modal odwiertow huba / Hub wells modal
    'wells_none'     => t('logistics.hub.wells_none'),
    'col_well'       => t('logistics.hub.wells_col_well'),
    'col_region'     => t('logistics.hub.wells_col_region'),
    'col_prod'       => t('logistics.hub.wells_col_prod'),
    'col_status'     => t('logistics.hub.wells_col_status'),
    'col_actions'    => t('logistics.hub.wells_col_actions'),
    'btn_detach'     => t('logistics.hub.wells_btn_detach'),
    'btn_transfer'   => t('logistics.hub.wells_btn_transfer'),
 // Modal transferu / Transfer modal
    'transfer_none'  => t('logistics.hub.transfer_none'),
 // Modal przypisania odwiertu / Well assign modal
    'assign_well_title' => t('logistics.hub.assign_well_title'),
    'assign_well_none'  => t('logistics.hub.assign_well_none'),
    'btn_assign_well'   => t('logistics.hub.btn_assign_well'),
    'btn_assign'        => t('logistics.hub.avail_btn_assign'),
 // Dostepne huby / Assignable hubs
    'avail_title'    => t('logistics.hub.avail_title'),
    'avail_none'     => t('logistics.hub.avail_none'),
    'avail_slots'    => t('logistics.hub.avail_slots',    ['free' => '{free}', 'total' => '{total}']),
    'avail_zone_pen' => t('logistics.hub.avail_zone_penalty', ['pct' => '{pct}']),
    'avail_fee'      => t('logistics.hub.avail_fee',      ['fee' => '{fee}']),
 // Condition labels.
    'cond_critical_short'     => t('logistics.hub.cond_critical_short'),
    'cond_low_short'          => t('logistics.hub.cond_low_short'),
    'warn_condition_critical' => t('logistics.hub.warn_condition_critical'),
    'warn_condition_low'      => t('logistics.hub.warn_condition_low'),
 // Hub type labels.
    'type_small'     => t('logistics.hub.type_small'),
    'type_medium'    => t('logistics.hub.type_medium'),
    'type_large'     => t('logistics.hub.type_large'),
 // Operation mode labels.
    'mode_eco'       => t('logistics.hub.mode_eco'),
    'mode_standard'  => t('logistics.hub.mode_standard'),
    'mode_max'       => t('logistics.hub.mode_max'),
 // Pagination labels.
    'pagination_prev'=> t('logistics.hub.pagination_prev'),
    'pagination_next'=> t('logistics.hub.pagination_next'),
 // Model pozyskania / Acquisition type labels
    'acq_new'        => t('logistics.hub.acquisition_new'),
    'acq_used'       => t('logistics.hub.acquisition_used'),
    'acq_rental'     => t('logistics.hub.acquisition_rental'),
    'acq_title'      => t('logistics.hub.acq_title'),
    'acq_wear'       => t('logistics.hub.acq_wear'),
    'acq_risk'       => t('logistics.hub.acq_risk'),
    'acq_opex'       => t('logistics.hub.acq_opex'),
    'acq_start_cond' => t('logistics.hub.acq_start_cond'),
    'acq_lease'      => t('logistics.hub.acq_lease'),
 // Rental confirmations and messages.
    'confirm_rental'          => t('logistics.hub.confirm_rental'),
    'confirm_rental_transfer' => t('logistics.hub.confirm_rental_transfer'),
    'ok_assign_with_lease'    => t('logistics.hub.ok_assign_with_lease'),
    'ok_assign_with_fee'      => t('logistics.hub.ok_assign_with_fee',   ['fee' => '{fee}']),
    'ok_transfer_with_lease'  => t('logistics.hub.ok_transfer_with_lease'),
 // Assignment cost breakdown confirmation.
    'confirm_assign_costs'    => t('logistics.hub.confirm_assign_costs'),
    'confirm_access_fee'      => t('logistics.hub.confirm_access_fee'),
    'confirm_usage_fee'       => t('logistics.hub.confirm_usage_fee'),
    'confirm_lease_fee'       => t('logistics.hub.confirm_lease_fee'),
    'confirm_per_tick'        => t('logistics.hub.confirm_per_tick'),
    'confirm_question'        => t('logistics.hub.confirm_question'),
    'err_insufficient_funds'  => t('logistics.hub.err_insufficient_funds'),
 // Hub market labels.
    'market_confirm_buy'       => t('logistics.hub.market_confirm_buy',  ['name' => '{name}', 'price' => '{price}']),
    'market_confirm_buy_title' => t('logistics.hub.market_confirm_buy_title'),
    'market_confirm_rent'      => t('logistics.hub.market_confirm_rent', ['name' => '{name}', 'deposit' => '{deposit}', 'lease' => '{lease}']),
    'market_confirm_rent_title'=> t('logistics.hub.market_confirm_rent_title'),
    'market_confirm_buy_new'  => t('logistics.hub.market_confirm_buy_new', ['name' => '{name}', 'price' => '{price}']),
    'market_ok_buy'           => t('logistics.hub.ok_buy_used'),
    'market_ok_rent'          => t('logistics.hub.ok_rent'),
    'market_ok_buy_new'       => t('logistics.hub.ok_buy_new'),
    'market_name_required'    => t('logistics.hub.market_name_required'),
    'err_hub_already_owned'   => t('logistics.hub.err_hub_already_owned'),
    'err_hub_already_rented'  => t('logistics.hub.err_hub_already_rented'),
    'err_hub_unavailable'     => t('logistics.hub.err_hub_unavailable'),
 // Local permit modal labels.
    'permit_modal_title' => t('legal.hub.permit_modal_title'),
    'permit_btn_cancel'  => t('legal.hub.permit_btn_cancel'),
    'permit_btn_apply'   => t('legal.hub.permit_btn_apply'),
    'permit_btn_legal'   => t('legal.hub.permit_btn_legal'),
    'permit_url'         => '/legal',
 // Well status labels for hub wells modal.
    'ws_active'          => t('technical.ws_active'),
    'ws_paused_staff'    => t('technical.ws_paused_staff'),
    'ws_paused_cash'     => t('technical.ws_paused_cash'),
    'ws_paused_storage'  => t('technical.ws_paused_storage'),
    'ws_contaminated'    => t('technical.ws_contaminated'),
    'ws_blowout'         => t('technical.ws_blowout'),
    'ws_seized'          => t('technical.ws_seized'),
    'ws_broken'          => t('technical.ws_broken'),
    'ws_no_operator'     => t('technical.ws_no_operator'),
    'ws_no_technician'   => t('technical.ws_no_technician'),
    'ws_sold'            => t('technical.ws_sold'),
    'ws_layer_switch'    => t('technical.ws_layer_switch'),
    ],
];
